First attemt to solution
grovestreetforlife/go_final_project pull request #1
Opened 2024-04-10 14:05 UTC by grovestreetforlife

1 попытка
Делал строго по ТЗ, подгоняя под тесты

2024-04-10 15:30 UTC, dirtymew requested changes
Привет Роман

отличная работа -  приложение запускается, тесты работают

как я понимаю задание авторизацию и dokerfile решено не делать? почему?
по докеру было задание в курсе - не должно составить проблем... 

проект можно сильно лучше сделать если код структурировать см https://github.com/golang-standards/project-layout
и доделать запуск в Docker-е 

ну и авторизацию тоже вроде не сложно добавить и все задания со звездочкой

если нет желания то надо поправить api и вернуть на review

2024-04-10 15:30 UTC, dirtymew commented on .idea/dataSources.local.xml
> +<?xml version="1.0" encoding="UTF-8"?>
это обычно не комитят в репозиторий - а добавляют в .gitignore

2024-04-10 15:30 UTC, dirtymew commented on server.go
> +	log.Println("Listening on port" + Port)
отлично - понятно что приложение запущено

2024-04-10 15:30 UTC, dirtymew commented on server.go
> +	//http.Handle("/api/task/done", http.HandlerFunc(taskDone))
по заданию  - нужно чтоб все эндпоинты работали
```
API содержит следующие операции:
добавить задачу;
получить список задач;
удалить задачу;
получить параметры задачи;
изменить параметры задачи;
отметить задачу как выполненную.
```

2024-04-10 15:33 UTC, grovestreetforlife commented on server.go
> +	//http.Handle("/api/task/done", http.HandlerFunc(taskDone))
Если правильно понял - у меня в свитче func task() перебирает методы


А здесь я попробовал 1 сделать используя встроенный в го маршрутизатор

2024-04-10 15:35 UTC, grovestreetforlife commented
Если честно, очень много с чистой архитектурой видел подходов, и как-то на ней застрял, пытаясь этот код переделать;
Со звездочками хотел попробовать сделать после зачтения обязательных задач

2024-04-10 15:36 UTC, grovestreetforlife commented on .idea/dataSources.local.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Да, это моя ошибка, я в основном в vsc работаю, а тут goland открывал для просмотра бд
Папку .idea удалил, но чуть раньше уже сделал git add и не заметил

Поправлю, спасибо!

2024-04-10 19:17 UTC, grovestreetforlife commented
upd.
Поправил эндпоинты и удалил файлы голанда
Проверил go test ./tests - все ок

2024-04-11 07:23 UTC, dirtymew requested changes
Привет Роман

отлично что тесты заработали

теперь нужно сделать большой рефакторинг  и работающие тесты помогут в этом.
после рефакторинга все должно также работать и тесты и приложение


Как я понимаю потом уже задания со звездочкой никто проверять не будет - если хочешь их сделать делай сейчас

2024-04-11 07:23 UTC, dirtymew commented on README.md
> +go test ./tests
лучше вот так go test ./...

2024-04-11 07:23 UTC, dirtymew commented on main.go
> +	err = Server()
тут с архитектурой решения проблемы - все слои смешались.
нужно переделать - отрефакторить.

вернись к заданию про посылки там сделано верно разделение на слои storage и server

 - слой storage - там все взаимодействие с бд - инициализация и все запросы
 - слой server логика - вся логика - взаимодейстие с storage и с transport/api
 - api/transport endpoint-ы взаимодействия с внешним миром/frontend

2024-04-11 07:23 UTC, dirtymew commented on server.go
> +	db, err := OpenDB()
на каждый запрос по подлючению это очень не оптимально

коннект к бд один раз при запуске приложения инициируй и храни в storage

2024-04-11 07:23 UTC, dirtymew commented on server.go
> +	for rows.Next() {
все взаимодейстие с бд в storage перенеси

2024-04-11 07:27 UTC, dirtymew commented
> Если честно, очень много с чистой архитектурой видел подходов, и как-то на ней застрял, пытаясь этот код переделать; Со звездочками хотел попробовать сделать после зачтения обязательных задач

чистая или не чистая не важно - тут все равно с архитектурой не очень все смешалось, будем рефакторить.

2024-04-11 08:19 UTC, grovestreetforlife commented
> Привет Роман
> 
> 
> 
> отлично что тесты заработали
> 
> 
> 
> теперь нужно сделать большой рефакторинг  и работающие тесты помогут в этом.
> 
> после рефакторинга все должно также работать и тесты и приложение
> 
> 
> 
> 
> 
> Как я понимаю потом уже задания со звездочкой никто проверять не будет - если хочешь их сделать делай сейчас

Добрый день,
 хорошо, займусь исправлениями; спасибо, что подсветили! :)

2024-04-11 14:19 UTC, grovestreetforlife commented
Проверил на тестах - всё ок
Разобрал между бд и сервером функции

2024-04-11 21:11 UTC, grovestreetforlife commented
Сделал ещё один коммит
Подчистил функции не нужные, и доработал по архитектуре

2024-04-12 11:59 UTC, dirtymew requested changes
Привет Роман

по архитектуре стало лучше - но еще надо доделать

как станет все с ней ок - приступим к ревью кода логики, если сейчас все смешать то запутаемся

2024-04-12 11:59 UTC, dirtymew commented on README.md
> +(если ./... говорит, что в других папках тестов нет)
это  как раз ок) зато когда там они появятся не нужно будет readme переписывать)

2024-04-12 11:59 UTC, dirtymew commented on database.go
> +	Query(query string, args ...interface{}) (*sql.Rows, error)
Это лишнее в интефейсе

Query и Exec это интефейс бд - а нам не бд нужно а хранилище для задач

2024-04-12 11:59 UTC, dirtymew commented on database.go
> +type Database interface {
тут лучше назвать storage или taskStorage И так далее 

нужно абстрагироваться от того **как** мы храним - нужна абстракция для того **что** мы храним

2024-04-12 11:59 UTC, dirtymew commented on main.go
> +	DBName = "./scheduler.db"
Почему часть констант экспортируемая а часть нет?

2024-04-12 11:59 UTC, dirtymew commented on dates.go
> +type Meths interface {
это непонятная абстакция - файл называется dates а интерфейс и структры Meth( интересно что это значит ?)

я думаю оно вообще лишняя и ее стоит убрать

2024-04-12 11:59 UTC, dirtymew commented on dates.go
> +func (m *Meth) ValidTask(t *models.Task) (*models.Task, error) {
это может быть просто метол структуры Task

и наверное ValidateAndModify ? раз он что-то делает с данными

2024-04-12 11:59 UTC, dirtymew commented on dates.go
> +func (m *Meth) NextDate(now time.Time, date string, repeat string) (string, error) {
если это какая-то сущность то для нее нужна структура - не понимаю чтоэто и почему тут

2024-04-12 11:59 UTC, dirtymew commented on models/tasks.go
> +	Id int64 `json:"id"`
тут что-то странное - ID в task это срока
тут это int
в бд храним int - надо тут порядок навести

2024-04-12 11:59 UTC, dirtymew commented on models/tasks.go
> +package models
почему это в models? а все остальное в корне?

по хорошему нужно разделить код по покетам https://github.com/golang-standards/project-layout

самому будет проще понимать архитектуру -  если пока сложно то лучше все в главном пакете делать...

2024-04-12 11:59 UTC, dirtymew commented on server.go
> +func NewServer(meth Meths) *Server {
тут бы я разделил на 2 слоя

- это api - все что связано с http, старт сервера, хендлеры, обработка реквестов в зависимостях у него server
- server - у него в зависимостях storage и он делает манипуляции с тасками

Например
```
handler taskDone
получил request - проверил id и вызвал один метод server 

server func taskDone
получил task(GetTaskById) удалил(DeleteTask) обновил И так далее - отдал ошибку

```

2024-04-12 12:08 UTC, grovestreetforlife commented on main.go
> +	DBName = "./scheduler.db"
> Почему часть констант экспортируемая а часть нет?

DBNme использовал в другом файле для инициализации бд (раньше)
Пересмотрю подход, спасибо что подсветили :)

2024-04-12 12:09 UTC, grovestreetforlife commented on dates.go
> +type Meths interface {
Изначально был "Methods", но при первых потугах сделать зависимости - пришлось редактировать имена и остановился на этом

2024-04-12 12:12 UTC, grovestreetforlife commented on dates.go
> +func (m *Meth) ValidTask(t *models.Task) (*models.Task, error) {
> это может быть просто метол структуры Task
> 
> и наверное ValidateAndModify ? раз он что-то делает с данными

Даа, я вот вчера на счет него думал:
Сначала он был просто функцией, но принял решение его к интерфейсу подвести

2024-04-12 12:13 UTC, grovestreetforlife commented on dates.go
> +func (m *Meth) NextDate(now time.Time, date string, repeat string) (string, error) {
> если это какая-то сущность то для нее нужна структура - не понимаю чтоэто и почему тут

Как и validtask проверяет repeat и меняет дату, так же сначала был просто функцией, но решил подвести к интерфейсу

2024-04-12 12:15 UTC, grovestreetforlife commented on models/tasks.go
> +	Id int64 `json:"id"`
> тут что-то странное - ID в task это срока тут это int в бд храним int - надо тут порядок навести

В тз для тестов была просьба вернуть id в джейсоне, если всё ок, и решил вместо Itoa сразу в эту структуру lastinsertId писать и отправлять в ответ

2024-04-12 12:15 UTC, grovestreetforlife commented on models/tasks.go
> +package models
> почему это в models? а все остальное в корне?
> 
> по хорошему нужно разделить код по покетам https://github.com/golang-standards/project-layout
> 
> самому будет проще понимать архитектуру - если пока сложно то лучше все в главном пакете делать...

Понял, попробую распределить по папкам

2024-04-12 12:16 UTC, grovestreetforlife commented on server.go
> +func NewServer(meth Meths) *Server {
> тут бы я разделил на 2 слоя
> 
> * это api - все что связано с http, старт сервера, хендлеры, обработка реквестов в зависимостях у него server
> * server - у него в зависимостях storage и он делает манипуляции с тасками
> 
> Например
> 
> ```
> handler taskDone
> получил request - проверил id и вызвал один метод server 
> 
> server func taskDone
> получил task(GetTaskById) удалил(DeleteTask) обновил И так далее - отдал ошибку
> ```

Спасибо, что подсветили
Пытался прийти к этому, но отвлёкся

2024-04-15 15:33 UTC, dirtymew requested changes
Привет Роман

стало намного лучше - все упростилось

есть что еще поправить см PR

2024-04-15 15:33 UTC, dirtymew commented on database.go
> +	if err := rows.Close(); err != nil {
лучше через defer  после инициализации курсора иначе если выйти из функции раньше - например при ошибке курсор останется открытым

2024-04-15 15:33 UTC, dirtymew commented on database.go
> +		return nil, ErrSqlExec
тут ты прячишь ошибку - могут быть проблемы при диагностике

лучше ее обернуть - причем даже не тут а выше уровнем....

2024-04-15 15:33 UTC, dirtymew commented on database.go
> +		return &Task{}, ErrSqlExec
лучше return nil, err

2024-04-15 15:33 UTC, dirtymew commented on models.go
> +package main
лучше переименовать в tasks.go

2024-04-15 15:33 UTC, dirtymew commented on converter.go
> +package main
методы нужно определять там же где и структуры

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +func (s *Server) task(w http.ResponseWriter, r *http.Request) {
я бы все хендлены определял явно в одном месте так проще будет понимать код

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +	http.Handle("/", http.FileServer(http.Dir(webDir)))
хендлеры в конструтор нужно перенести в запуске зачем их обьявлять?

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +type TodoL interface {
название не в go стиле - лучше переназвать

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +	w.WriteHeader(http.StatusOK)
тут случайно не 201 код?

2024-04-15 15:33 UTC, dirtymew commented on models.go
> +	ID      string `json:"id"`
ну вот это прям странно получилось... если тесты  и фронт написаны под json строкой то тогда лучше везде строки использовать

а бд можно и уйти от автоинремента и просто использовать уникальный индекс на поле или uuid timestamp И так далее или на уровне стораджа конвертировать структуры...

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +		s.taskPost(w, r)
createTask

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +		s.taskPut(w, r)
updateTask

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +		s.getById(w, r)
getTask

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +		s.taskDelete(w, r)
deleteTask

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +	http.Handle("/api/tasks", http.HandlerFunc(s.getAll))
предлагаю такие названия функциям getTasks

2024-04-15 15:33 UTC, dirtymew commented on server.go
> +	err = s.m.DeleteTask(uint64(id))
uint64 - мне кажется не стоит этого чтобы вот так с типами морочиться - да и числовыой id-ник не кажется в принципе хорошей идеей

2024-04-15 15:37 UTC, grovestreetforlife commented on models.go
> +	ID      string `json:"id"`
Да, у меня сначала была 1 структура со стрингой, без листов и прочего, но потом решил поменять на юинт
Из-за того, что id везде строка - пришлось костылить и появились структуры для маршала в джейсон

2024-04-15 18:06 UTC, grovestreetforlife commented on models.go
> +	ID      string `json:"id"`
> ну вот это прям странно получилось... если тесты и фронт написаны под json строкой то тогда лучше везде строки использовать
> 
> а бд можно и уйти от автоинремента и просто использовать уникальный индекс на поле или uuid timestamp И так далее или на уровне стораджа конвертировать структуры...

Осталось разобраться с типом id
Мне кажется, что удобнее было бы его числовым завести и использовать автоинкремент -> а вот на конвертации подвис: то ли прямо внутри database.go id строку приводить к числу, то ли в сервере (ведь если бд поменяем, суть не поменяется - получаем id строкой всё равно)

2024-04-15 18:14 UTC, grovestreetforlife commented
PR  отправил, чтобы посоветоваться, как лучше поступить с типом id:
- Можно его оставить числом в бд, и внутри database.go его конвертить string->int, int->string?

2024-04-15 20:14 UTC, grovestreetforlife commented
Пошел по пути структуры со стрингом и конвертацией в число и обратно в слое бд: 
Убрал структуры и методы JSON, откорректировал интерфейсы и методы, поправил логику, убрал лишние проверки

2024-04-16 08:06 UTC, dirtymew commented
> PR отправил, чтобы посоветоваться, как лучше поступить с типом id:
> 
> * Можно его оставить числом в бд, и внутри database.go его конвертить string->int, int->string?

Да то выход - так в целом можно

2024-04-16 08:10 UTC, grovestreetforlife commented
> > PR отправил, чтобы посоветоваться, как лучше поступить с типом id:
> 
> > 
> 
> > * Можно его оставить числом в бд, и внутри database.go его конвертить string->int, int->string?
> 
> 
> 
> Да то выход - так в целом можно

Добрый день,
Супер! 
Вчера вторым комитом такой вариант сделал-запушил🫡

2024-04-16 08:20 UTC, dirtymew requested changes
Привет Роман

дал комментарии 

вопрос - ты будешь делать задания со звездочкой?

если да то делай сейчас...
если нет то поправить по комментариям и возвращай

2024-04-16 08:20 UTC, dirtymew commented on main.go
> +	if err != nil {
тут лучше так 

```
if err = server.Start(); err != nil {
```

2024-04-16 08:20 UTC, dirtymew commented on todolist.go
> +func (m *Storage) GetTaskById(id string) (*Task, error) {
название плохое - просто GetTask

2024-04-16 08:20 UTC, dirtymew commented on todolist.go
> +type Storage struct {
и это все-таки не storage а service

и файл service.go

2024-04-16 08:20 UTC, dirtymew commented on database.go
> +type SQLDatabase struct {
SQLDatabase - плохое название - предлагаю Storage

и файл storage.go

2024-04-16 08:20 UTC, dirtymew commented on todolist.go
> +func (m *Storage) ValidTaskAndModify(t *Task) (*Task, error) {
это похоже на метод структуры Task

2024-04-16 08:28 UTC, grovestreetforlife commented
> Привет Роман
> 
> 
> 
> дал комментарии 
> 
> 
> 
> вопрос - ты будешь делать задания со звездочкой?
> 
> 
> 
> если да то делай сейчас...
> 
> если нет то поправить по комментариям и возвращай

Мне бы с моими успехами простые задания сделать😄 кажется, что много времени на них потратил;
Посмотрю, что смогу сделать; но думаю, что не осилю

2024-04-17 22:22 UTC, dirtymew requested changes
Привет Роман

про задания со звездочкой понятно - принято

Допиши readme и разберись с интерфейсом и будет ок

2024-04-17 22:22 UTC, dirtymew commented on service.go
> +type Database interface {
просмотрел чтоли - интерфейс не используется никак - тут либо его использовать или удалить надо

2024-04-18 22:42 UTC, dirtymew approved these changes
Привет Роман

зачет, жаль что не попробовал сдать со звездочкой - уверен у тебя все получилось.

Удачи в обучении

2024-04-19 05:49 UTC, grovestreetforlife commented
> Привет Роман
> 
> 
> 
> зачет, жаль что не попробовал сдать со звездочкой - уверен у тебя все получилось.
> 
> 
> 
> Удачи в обучении

Спасибо 🫡

2024-05-22 12:13 UTC, merged